const formattedPackages = [
    {
      numberOfPeople: 50,
      packageName: "বিবাহ",
      packageImg: "https://i.ibb.co.com/Z6RNcpQf/Food-packaging-mockup.jpg",
      packageDes: "বিবাহ অনুষ্ঠান উপলক্ষে ঐতিহ্যবাহী ও সুস্বাদু খাবারের আয়োজন।",
      childrenPackageName: "ছোট প্যাকেজ",
      childrenPackageImg: "/images/small-package.jpg",
      childrenPackageDescriptionSmall: "মিষ্টি, নিমকি।",
      childrenPackageDescriptionLarge:
        "ছোট প্যাকেজে থাকছে মিষ্টি এবং নিমকি। সুস্বাদু ও হালকা খাবারের আয়োজন।",
      childrenPackagePrice: 3000,
    },
    {
      numberOfPeople: 100,
      packageName: "বিবাহ",
      packageImg: "https://i.ibb.co.com/Z6RNcpQf/Food-packaging-mockup.jpg",
      packageDes: "বিবাহ অনুষ্ঠান উপলক্ষে ঐতিহ্যবাহী ও সুস্বাদু খাবারের আয়োজন।",
      childrenPackageName: "মিডিয়াম প্যাকেজ",
      childrenPackageImg: "/images/medium-package.jpg",
      childrenPackageDescriptionSmall: "মিষ্টি, নিমকি, জিলাপি।",
      childrenPackageDescriptionLarge:
        "মিডিয়াম প্যাকেজে থাকছে মিষ্টি, নিমকি এবং জিলাপি। অতিথিদের জন্য আদর্শ।",
      childrenPackagePrice: 5000,
    },
    {
      numberOfPeople: 150,
      packageName: "বিবাহ",
      packageImg: "https://i.ibb.co.com/Z6RNcpQf/Food-packaging-mockup.jpg",
      packageDes: "বিবাহ অনুষ্ঠান উপলক্ষে ঐতিহ্যবাহী ও সুস্বাদু খাবারের আয়োজন।",
      childrenPackageName: "বড় প্যাকেজ",
      childrenPackageImg: "/images/large-package.jpg",
      childrenPackageDescriptionSmall: "মিষ্টি, সিঙ্গারা, চমচা।",
      childrenPackageDescriptionLarge:
        "বড় প্যাকেজে থাকছে মিষ্টি, সিঙ্গারা, চমচা এবং চমচা মিষ্টি।",
      childrenPackagePrice: 7000,
    },
    {
      numberOfPeople: 200,
      packageName: "বিবাহ",
      packageImg: "https://i.ibb.co.com/Z6RNcpQf/Food-packaging-mockup.jpg",
      packageDes: "বিবাহ অনুষ্ঠান উপলক্ষে ঐতিহ্যবাহী ও সুস্বাদু খাবারের আয়োজন।",
      childrenPackageName: "ডিলাক্স প্যাকেজ",
      childrenPackageImg: "/images/deluxe-package.jpg",
      childrenPackageDescriptionSmall: "মিষ্টি, নিমকি, জিলাপি, রসগোল্লা।",
      childrenPackageDescriptionLarge:
        "ডিলাক্স প্যাকেজে থাকছে মিষ্টি, নিমকি, জিলাপি এবং রসগোল্লা। বিবাহ অনুষ্ঠানের জন্য পারফেক্ট।",
      childrenPackagePrice: 10000,
    },
  
   
    {
      numberOfPeople: 20,
      packageName: "জন্মদিন",
      packageImg: "https://i.ibb.co.com/Rkb3fZHc/images.jpg",
      packageDes: "জন্মদিন উপলক্ষে সুস্বাদু ও মজাদার খাবারের আয়োজন।",
      childrenPackageName: "ছোট প্যাকেজ",
      childrenPackageImg: "/images/small-package.jpg",
      childrenPackageDescriptionSmall: "চকলেট কেক, পেস্ট্রি।",
      childrenPackageDescriptionLarge:
        "ছোট প্যাকেজে থাকছে চকলেট কেক এবং পেস্ট্রি। শিশুদের জন্য উপযোগী।",
      childrenPackagePrice: 1500,
    },
    {
      numberOfPeople: 30,
      packageName: "জন্মদিন",
      packageImg: "https://i.ibb.co.com/Rkb3fZHc/images.jpg",
      packageDes: "জন্মদিন উপলক্ষে সুস্বাদু ও মজাদার খাবারের আয়োজন।",
      childrenPackageName: "মিডিয়াম প্যাকেজ",
      childrenPackageImg: "/images/medium-package.jpg",
      childrenPackageDescriptionSmall: "কেক, জুস, স্যান্ডউইচ।",
      childrenPackageDescriptionLarge: "মিডিয়াম প্যাকেজে থাকছে কেক, জুস এবং স্যান্ডউইচ।",
      childrenPackagePrice: 2500,
    },
    {
      numberOfPeople: 40,
      packageName: "জন্মদিন",
      packageImg: "https://i.ibb.co.com/Rkb3fZHc/images.jpg",
      packageDes: "জন্মদিন উপলক্ষে সুস্বাদু ও মজাদার খাবারের আয়োজন।",
      childrenPackageName: "বড় প্যাকেজ",
      childrenPackageImg: "/images/large-package.jpg",
      childrenPackageDescriptionSmall: "কেক, জুস, স্যান্ডউইচ, আইসক্রিম।",
      childrenPackageDescriptionLarge: "বড় প্যাকেজে থাকছে কেক, জুস, স্যান্ডউইচ এবং আইসক্রিম।",
      childrenPackagePrice: 4000,
    },
    {
      numberOfPeople: 50,
      packageName: "জন্মদিন",
      packageImg: "https://i.ibb.co.com/Rkb3fZHc/images.jpg",
      packageDes: "জন্মদিন উপলক্ষে সুস্বাদু ও মজাদার খাবারের আয়োজন।",
      childrenPackageName: "ডিলাক্স প্যাকেজ",
      childrenPackageImg: "/images/deluxe-package.jpg",
      childrenPackageDescriptionSmall: "কেক, পেস্ট্রি, জুস, চকলেট।",
      childrenPackageDescriptionLarge: "ডিলাক্স প্যাকেজে থাকছে কেক, পেস্ট্রি, জুস এবং চকলেট।",
      childrenPackagePrice: 5000,
    },
    {
      numberOfPeople: 30,
      packageName: "অন্যান্য",
      packageImg: "https://i.ibb.co.com/fdghZrCT/download-3.jpg",
      packageDes: "বিভিন্ন উৎসব এবং অনুষ্ঠানের জন্য বিশেষ প্যাকেজ।",
      childrenPackageName: "ফ্যামিলি প্যাকেজ",
      childrenPackageImg: "/images/family-package.jpg",
      childrenPackageDescriptionSmall: "ভাত, ডাল, মাছ।",
      childrenPackageDescriptionLarge: "ফ্যামিলি প্যাকেজে থাকছে ভাত, ডাল এবং মাছ।",
      childrenPackagePrice: 2000,
    },
    {
      numberOfPeople: 70,
      packageName: "অন্যান্য",
      packageImg: "https://i.ibb.co.com/fdghZrCT/download-3.jpg",
      packageDes: "বিভিন্ন উৎসব এবং অনুষ্ঠানের জন্য বিশেষ প্যাকেজ।",
      childrenPackageName: "ভেজিটেরিয়ান প্যাকেজ",
      childrenPackageImg: "/images/vegetarian-package.jpg",
      childrenPackageDescriptionSmall: "সবজি, ডাল, রুটি।",
      childrenPackageDescriptionLarge: "ভেজিটেরিয়ান প্যাকেজে থাকছে সবজি, ডাল এবং রুটি।",
      childrenPackagePrice: 3000,
    },
    {
      numberOfPeople: 100,
      packageName: "অন্যান্য",
      packageImg: "https://i.ibb.co.com/fdghZrCT/download-3.jpg",
      packageDes: "বিভিন্ন উৎসব এবং অনুষ্ঠানের জন্য বিশেষ প্যাকেজ।",
      childrenPackageName: "স্পেশাল প্যাকেজ",
      childrenPackageImg: "/images/special-package.jpg",
      childrenPackageDescriptionSmall: "ভাত, মাংস, রেজালা।",
      childrenPackageDescriptionLarge: "স্পেশাল প্যাকেজে থাকছে ভাত, মাংস এবং রেজালা।",
      childrenPackagePrice: 5000,
    },
  ];
  
  export default formattedPackages;
  